version: '3.7'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./my-dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  gameserver:
    build: .
    ports:
      - '50051:50051'
    environment:
      - REDIS_ADDR=redis:6379
      - DYNAMO_ADDR=http://dynamodb:8000
    command: go run cmd/server/main.go
    depends_on:
      - "dynamodb"
      - "redis"
volumes:
  redis:
    driver: local