// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: proto/battle/battle.proto

package battle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId1 string `protobuf:"bytes,1,opt,name=playerId1,proto3" json:"playerId1,omitempty"`
	PlayerId2 string `protobuf:"bytes,2,opt,name=playerId2,proto3" json:"playerId2,omitempty"`
}

func (x *StartBattleRequest) Reset() {
	*x = StartBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_battle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleRequest) ProtoMessage() {}

func (x *StartBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_battle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleRequest.ProtoReflect.Descriptor instead.
func (*StartBattleRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_battle_proto_rawDescGZIP(), []int{0}
}

func (x *StartBattleRequest) GetPlayerId1() string {
	if x != nil {
		return x.PlayerId1
	}
	return ""
}

func (x *StartBattleRequest) GetPlayerId2() string {
	if x != nil {
		return x.PlayerId2
	}
	return ""
}

type StartBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battleId,proto3" json:"battleId,omitempty"`
}

func (x *StartBattleResponse) Reset() {
	*x = StartBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_battle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattleResponse) ProtoMessage() {}

func (x *StartBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_battle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattleResponse.ProtoReflect.Descriptor instead.
func (*StartBattleResponse) Descriptor() ([]byte, []int) {
	return file_proto_battle_battle_proto_rawDescGZIP(), []int{1}
}

func (x *StartBattleResponse) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

type FinishBattleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId string `protobuf:"bytes,1,opt,name=battleId,proto3" json:"battleId,omitempty"`
	WinnerId string `protobuf:"bytes,2,opt,name=winnerId,proto3" json:"winnerId,omitempty"`
}

func (x *FinishBattleRequest) Reset() {
	*x = FinishBattleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_battle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishBattleRequest) ProtoMessage() {}

func (x *FinishBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_battle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishBattleRequest.ProtoReflect.Descriptor instead.
func (*FinishBattleRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_battle_proto_rawDescGZIP(), []int{2}
}

func (x *FinishBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FinishBattleRequest) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

type FinishBattleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player1Score int64 `protobuf:"varint,1,opt,name=player1Score,proto3" json:"player1Score,omitempty"`
	Player2Score int64 `protobuf:"varint,2,opt,name=player2Score,proto3" json:"player2Score,omitempty"`
}

func (x *FinishBattleResponse) Reset() {
	*x = FinishBattleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battle_battle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishBattleResponse) ProtoMessage() {}

func (x *FinishBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_battle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishBattleResponse.ProtoReflect.Descriptor instead.
func (*FinishBattleResponse) Descriptor() ([]byte, []int) {
	return file_proto_battle_battle_proto_rawDescGZIP(), []int{3}
}

func (x *FinishBattleResponse) GetPlayer1Score() int64 {
	if x != nil {
		return x.Player1Score
	}
	return 0
}

func (x *FinishBattleResponse) GetPlayer2Score() int64 {
	if x != nil {
		return x.Player2Score
	}
	return 0
}

var File_proto_battle_battle_proto protoreflect.FileDescriptor

var file_proto_battle_battle_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x22, 0x50, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x32, 0x22, 0x31, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x32, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x9f, 0x01, 0x0a, 0x06, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6c, 0x65, 0x64, 0x6f, 0x6f, 0x6d,
	0x2f, 0x70, 0x6f, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_battle_battle_proto_rawDescOnce sync.Once
	file_proto_battle_battle_proto_rawDescData = file_proto_battle_battle_proto_rawDesc
)

func file_proto_battle_battle_proto_rawDescGZIP() []byte {
	file_proto_battle_battle_proto_rawDescOnce.Do(func() {
		file_proto_battle_battle_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_battle_battle_proto_rawDescData)
	})
	return file_proto_battle_battle_proto_rawDescData
}

var file_proto_battle_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_battle_battle_proto_goTypes = []interface{}{
	(*StartBattleRequest)(nil),   // 0: battle.StartBattleRequest
	(*StartBattleResponse)(nil),  // 1: battle.StartBattleResponse
	(*FinishBattleRequest)(nil),  // 2: battle.FinishBattleRequest
	(*FinishBattleResponse)(nil), // 3: battle.FinishBattleResponse
}
var file_proto_battle_battle_proto_depIdxs = []int32{
	0, // 0: battle.Battle.StartBattle:input_type -> battle.StartBattleRequest
	2, // 1: battle.Battle.FinishBattle:input_type -> battle.FinishBattleRequest
	1, // 2: battle.Battle.StartBattle:output_type -> battle.StartBattleResponse
	3, // 3: battle.Battle.FinishBattle:output_type -> battle.FinishBattleResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_battle_battle_proto_init() }
func file_proto_battle_battle_proto_init() {
	if File_proto_battle_battle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_battle_battle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_battle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_battle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishBattleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battle_battle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishBattleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_battle_battle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_battle_battle_proto_goTypes,
		DependencyIndexes: file_proto_battle_battle_proto_depIdxs,
		MessageInfos:      file_proto_battle_battle_proto_msgTypes,
	}.Build()
	File_proto_battle_battle_proto = out.File
	file_proto_battle_battle_proto_rawDesc = nil
	file_proto_battle_battle_proto_goTypes = nil
	file_proto_battle_battle_proto_depIdxs = nil
}
